### ISSUE TITLE
Cannot find name '__renew'.

### ISSUE THREAD

**Issue by 1vs9** [JairusSW/as-json#16]
code following

const myClassInstance= JSON.parse<myClass>(jsonString)

then i exec  `npm run asbuild`

it reports error following:
`ERROR TS2304: Cannot find name '__new'.

     this.buffer = changetype<ArrayBuffer>(__new(
                                           ~~~~~
 in ~lib/as-string-sink/index.ts(21,43)

ERROR TS2304: Cannot find name '__renew'.

       this.buffer = changetype<ArrayBuffer>(__renew(
                                             ~~~~~~~
 in ~lib/as-string-sink/index.ts(146,45)

ERROR TS2304: Cannot find name '__new'.

     let out = changetype<string>(__new(size, idof<string>()));
                                  ~~~~~
 in ~lib/as-string-sink/index.ts(136,34)`

**Comment by JairusSW** [comment]
Seems like something related to as-string-sink. Are you using the latest version of the AssemblyScript loader and language?
If it persists, ask in the AssemblyScript Discord

**Comment by JairusSW** [comment]
Closing this because it isn't directly related with as-json
