### ISSUE TITLE
ERROR TS1109: Expression expected with the decorator of `@json` 

### ISSUE THREAD

**Issue by tkblack** [JairusSW/as-json#24]
Hello, I get a error when i want to build the code below.
```
// @ts-ignore
    @json
    class student {
        name: string
        sex: string
        age: i32
    }

    let stu: student = {
        name: name,
        sex: sex,
        age: 18
    }

    let jsonStr = JSON.stringify(stu)
    //Console.log(`test_json: json: ${jsonStr}`)

    let parsed = JSON.parse<student>(jsonStr)
```

The error message like below.
```
> asc assembly/index.ts --target debug

ERROR TS1109: Expression expected.

     @json
     ~
 in assembly/index.ts(58,5)

FAILURE 1 parse error(s)

```

The version of assemblyscript is `0.19.22`.
I don't know why it happened. So, what could i do for this to solve the problem.

**Comment by JairusSW** [comment]
Sorry for getting back so late
Did you use `import { JSON } from "json-as";` at the top?
It seems like an issue with TypeScript which the ASC compiler piggybacks on top of.
Really odd issue. It worked on my end using the same version of AS

**Comment by tachyonicbytes** [comment]
Sorry to comment on a closed thread, but I had the same problem and this was the only information I could find on the issue, so I am writing here in case anybody in the future has the same problem.

I solved the problem by not declaring classes inside a function, declaring them outside and then just using them inside the function. The level of indentation in the original question makes me think that this was also the case for the original problem.

**Comment by JairusSW** [comment]
@tachyonicbytes, ah! That does make sense. The transform can't detect or stringify/parse class declarations inside of of functions and so it will give an error because the decorator is invalid if the transform can't view it

**Comment by tkblack** [comment]
@JairusSW @tachyonicbytes Thanks for your reply. I'll try it !
> I solved the problem by not declaring classes inside a function, declaring them outside and then just using them inside the function. The level of indentation in the original question makes me think that this was also the case for the original problem.

**Comment by JairusSW** [comment]
Closing this for now :)
