### ISSUE TITLE
Numeric field dropping digit on parse

### ISSUE THREAD

**Issue by rdraward** [JairusSW/as-json#29]
Awesome library, it saves a ton of time vs manual ser/de!

It looks like a digit is being dropped when trying to parse incoming numeric fields.
```
import "wasi";
import { Console } from "as-wasi/assembly";

@json
class Test {
  value: i64;
}

const t = JSON.stringify<Test>({ value: 20 });
const r = JSON.parse<Test>(t);
Console.log(JSON.stringify(r));
```
prints out `"value": 2,`

I also tried using a json string as input
```
const t = `{"value": 20}`;
const r = JSON.parse<Test>(t);
Console.log(JSON.stringify(r));
```
 which gives the same result `"value": 2,`

However, I am able to get things working if I inject a trailing comma into my input string:
```
const t = `{"value": 20,}`;
const r = JSON.parse<Test>(t);
Console.log(JSON.stringify(r));
```
which prints out `"value": 20`.

Adding another class property (ie. `valueTwo: i64`) results in only the last property getting improperly parsed:

```
@json
class Test {
  value: i64;
  valueTwo: i64;
}

const t = `{"value": 20, "valueTwo": 23}`;
const r = JSON.parse<Test>(t);
Console.log(JSON.stringify(r));
```
prints out ` "value": 20, "valueTwo": 2,` which makes me think there's just a final character being removed regardless of whether or not it is a comma.

**Comment by JairusSW** [comment]
I'm on it

**Comment by JairusSW** [comment]
Should be fixed with the latest release

**Comment by JairusSW** [comment]
Closing b/c fix is released
