### ISSUE TITLE
[ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './transform' is not defined by "exports"

### ISSUE THREAD

**Issue by Tinche** [JairusSW/as-json#36]
Hello!

I'm trying to get started with this library, not having too much experience with WASM, AssemblyScript or TypeScript for that matter.

I followed the instructions from the README, but when I invoke `asc` with `"transform": "json-as/transform"` in my options, I get the error from the title.

Would be great if you could help me with what I'm doing wrong. Thanks!

**Comment by JairusSW** [comment]
Hello!
You want to invoke `asc` with the `--transform json-as/transform` flag, not the JSON k/v pair.
Example: 
```js
asc assembly/index.ts --target debug --transform json-as/transform
```

**Comment by Tinche** [comment]
Sorry I expressed myself unclearly, I tried both unsuccessfully. 

I think there might be an issue with my project setup though, another library I needed to import using `"../node_modules/x"` instead of just `x`.

**Comment by JairusSW** [comment]
What version of AssemblyScript are you using? Are you invoking `asc` in the root directory of your project?

**Comment by JairusSW** [comment]
If you want to send me a screenshot or something, I would be willing to take a look

**Comment by JairusSW** [comment]
Found the problem. I ran `asinit .` and it messed with the exports. Releasing with the next version in a few minutes

**Comment by JairusSW** [comment]
Done.

**Comment by Tinche** [comment]
Thanks, that solved my issue!
