### ISSUE TITLE
JSON.stringify support leaving out null values?

### ISSUE THREAD

**Issue by mariusa** [JairusSW/as-json#38]
Hi,

Would it be possible to have a version of JSON.stringify which leaves out null values? (null values should be included by default, that is normal).

Here's why: https://github.com/AssemblyScript/assemblyscript/issues/2591
Basically, a limitation of being unable to declare them as optional and simply not set them. I realize this is a language limitation and by no means an issue with `as-json`, just trying to find a workaround.

Thanks

**Comment by JairusSW** [comment]
You can probably use a Variant
https://github.com/MaxGraey/as-variant

**Comment by mariusa** [comment]
Thanks!
