### ISSUE TITLE
Support optional serializing of properties

### ISSUE THREAD

**Issue by mattjohnsonpint** [JairusSW/as-json#52]
Consider:

```ts
@json
class Person {
  constructor(public firstName: string, public lastName: string) {}

  get fullName(): string {
    return `${this.firstName} ${this.lastName}`;
  }
};
```
...

```ts
const p = new Person("John", "Doe")
const s = JSON.stringify(p);
```
output:
```json
{"firstName":"John","lastName":"Doe"}
```

How might I indicate that I want `fullName` included in the output?

With JavaScript, I can do that by explicitly specifying the requested fields.  In other words:

```js
const s = JSON.stringify(p, ['firstName', 'lastName', 'fullName']);
```

I could see that working here as well.  Alternatively, perhaps we can do something with decorators on the property itself, such as:

```ts
  @json(include: true)
  get fullName(): string {
    return `${this.firstName} ${this.lastName}`;
  }
```

Thoughts?

**Comment by JairusSW** [comment]
Perhaps we could make it default to serialize/deserialize if a getter/setter pair exists which would be implemented in the transform.

I like the idea of having an option argument `JSON.stringify<T, C>(data: T, config: C): string`, but I'm not sure how deeply string matching would impact performance.

Another option *could* be to use some sort of comment...
```js
// include: fullName
@json
class Vec3 {
class Person {
  constructor(public firstName: string, public lastName: string) {}

  get fullName(): string {
    return `${this.firstName} ${this.lastName}`;
  }
}
```

Any of these could totally be implemented. I ordered them top-to-bottom for complexity

**Comment by JairusSW** [comment]
@casimiro, looping you in here.
Supporting default values (https://github.com/JairusSW/as-json/issues/51) kind of loops in here.
Currently, as-json just allocates empty space for the class, so default values and all values are uninitialized.

One other solution here is to parse *out* to a object, string, number, variable, ect..
```js
@json
class Vec3 {
    x: f64 = 3.4;
    y: f64 = 1.2;
    z: f64 = 8.3;
}

const parsedVec = new Vec3();
// Default values initialized. Do whatever logic you want here.

JSON.parseTo<Vec3>(parsedVec, '{"y":8.4}');

console.log(JSON.stringify(parsedVec));
// {
//    "x": 3.4,
//    "y": 8.4,
//    "z": 8.3
// }
```

**Comment by casimiro** [comment]
@JairusSW I really like the idea of parsing out to an object -- it favours efficiency and the interface remains simple and clear.

**Comment by JairusSW** [comment]
I'm on Thanksgiving break, so I'm planning to spend some time on this. :)

**Comment by JairusSW** [comment]
Implemented in latest version. I will implement parsing out to an object later as that is really cool
