### ISSUE TITLE
How to alias fields?

### ISSUE THREAD

**Issue by mattjohnsonpint** [JairusSW/as-json#57]
Sometimes you might have json keys that don't align one-to-one with an object's field names, or you might have a json key that _cannot_ be a field name in AssemblyScript.  For example:

```json
{
  "first name": "John"
  "last name": "Doe"
}
```

I would need an object to deserialize to:

```ts
@json
class Person {
  firstName!: string;
  lastName!: string;
}
```

So how do I indicate that the `"first name"` key goes to the `firstName` field, etc.?  Since the key contains a space, it cannot directly be the field name.  There are other use cases as well, such as when a field and its json key differ in casing, or when a json key starts with a `@` or `$`, etc.

The same goes for serialization - I might need the json key to be different than the field name in the generated json.

**Comment by JairusSW** [comment]
Hm, good question.
I'll have to look into a solution

**Comment by mattjohnsonpint** [comment]
FYI, in JavaScript, you do this with a `replacer` function in the second parameter of `JSON.stringify`, or a `reviver` function in `JSON.parse`.

```js
const reviver =  function (key, value) {
    switch (key) {
        case 'first name':
            this.firstName = value;
            return undefined;
        case 'last name':
            this.lastName = value;
            return undefined;
        default:
            return value;
    }
};
const person = JSON.parse('{"first name":"John","last name":"Doe"}', reviver);
```

The inverse is more challenging, but is possible.  See https://stackoverflow.com/a/5480605/634824

In Go, it's built-in and more declarative:

```go
type Person struct {
    FirstName  string  `json:"first name"`
    LastName   string  `json:"last name"`
}
```

In C# it's done with attributes (ie. decorators):

```csharp
public class Person
{
    [JsonPropertyName("first name")]
    public String FirstName { get; set; }

    [JsonPropertyName("last name")]
    public String LastName { get; set; }
}
```

IMHO, It would be useful if in AssemblyScript it would be like the latter two.  Perhaps:

```ts
@json
class Person {
  firstName!: string; @jsonKey("first name")
  lastName!:  string; @jsonKey("last name")
}
```

**Comment by JairusSW** [comment]
Feature brought version 0.7.0
