### ISSUE TITLE
Error building the project with as-json

### ISSUE THREAD

**Issue by spino17** [JairusSW/as-json#72]
I installed the `as-json` and tried to build the project with `npm run asbuild`. It is giving below error:
```FAILURE Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'visitor-as' imported from```.

I have followed the instructions of attaching the `--transform` option etc.

**Comment by mattjohnsonpint** [comment]
I'm not sure if there's a better way, but what I've had success with is as follows:

- `npm install json-as`
-  add the following to the `package.json` file manually:
  ```json
  "overrides": {
    "assemblyscript": "$assemblyscript"
  }
  ```
- `npm install -D visitor-as`

The resulting `package.json` should have all of the following (with whatever the current versions are):

```json
  "dependencies": {
    "json-as": "^0.8.4"
  },
  "devDependencies": {
    "assemblyscript": "^0.27.27",
    "visitor-as": "^0.11.4"
  },
  "overrides": {
    "assemblyscript": "$assemblyscript"
  }
```

And then, yes - you still need the transform, either on the command line when calling `asc`, or in the `asconfig.json`.

**Comment by JairusSW** [comment]
I made it so that the end user can install a different version of `visitor-as` say if they were targeting AssemblyScript `v18.x.x`, they would install an older version for compat. I try to keep this lib backwards compatible with older versions :)
