### ISSUE TITLE
Feature request: Support serializing of boxed nullable primitives

### ISSUE THREAD

**Issue by mattjohnsonpint** [JairusSW/as-json#73]
This library supports nullable strings already.  Ie., this will serialize/deserialize:

```ts
@json
class Foo {
  optionalString: string | null = null;
}
```

But there's an AssemblyScript restriction that only managed types can be nullable, so nullable primitives are not allowed:

```ts
@json
class Foo {
  optionalNumber: i32 | null = null;  // compiler error
  tristateValue: bool | null = null;  // compiler error
}
```

We can use `Box<T>` from [as-container](https://github.com/yjhmelody/as-container) instead:

```ts
@json
class Foo {
  optionalNumber: Box<i32> | null = null;
  tristateValue: Box<bool> | null = null;
}
```

But these aren't serializable/deserializable in json-as.

Whether through `Box<T>` or through some other mechanism, there needs to be some way to work with JSON containing nullable primitives.

Note, this is related to #70 - but slightly different.  (A field value sent as `null` vs. the field being omitted.)

**Comment by mattjohnsonpint** [comment]
Errors when trying to use `Box<T> | null` are:

```
ERROR TS2322: Type '~lib/as-container/assembly/box/Box<i32> | null' is not assignable to type '~lib/as-container/assembly/box/Box<i32>'.
     :
 902 │ } else if (isNullable<T>() && data == null) {
     │                               ~~~~
     └─ in ~lib/json-as/assembly/src/json.ts(902,33)

ERROR TS2322: Type '~lib/as-container/assembly/box/Box<i32> | null' is not assignable to type '~lib/as-container/assembly/box/Box<i32>'.
     :
 902 │ } else if (isNullable<T>() && data == null) {
     │                                       ~~~~
     └─ in ~lib/json-as/assembly/src/json.ts(902,41)

FAILURE 2 compile error(s)
Build failed.
```

**Comment by mattjohnsonpint** [comment]
... and I suppose if `Box<T> | null` works, then `Box<T>` (non-null) should work as well.

**Comment by JairusSW** [comment]
@mattjohnsonpint, perhaps I can implement custom serializers...
Something like this:

```js
import { Box } from "as-container/assembly";

function serializeBox<T extends Box<any>>(data: T): string {
   // basic preprocessing
   if (isNullable<T>() && data == null) return "null";
   // Else, delegate to json-as
   return JSON.serialize(data.value);
 }
 
 function deserializeBox<T extends Box<any>>(data: string): T {
   return Box.from(JSON.parse<valueof<T>>(data));
 }
 
 JSON.register(serializeBox, deserializeBox);
```

**Comment by mattjohnsonpint** [comment]
That would be very nice, and would prevent adding a dependency.  I'm sure there are plenty of other cases where that would be useful also.

**Comment by JairusSW** [comment]
I added support natively. Should work now
