### ISSUE TITLE
Feature request: Support raw JSON string properties

### ISSUE THREAD

**Issue by mattjohnsonpint** [JairusSW/as-json#88]
I need to be able to serialize/deserialize a class where some field is arbitrary JSON.  For example, given this class:

```ts
@json
class Foo {
  value: string;
}
```

If I set `bar` to a string having the value `{"a":1,"b":false,"c":"abc"}` then _normally_ when serializing `Foo` I would get:

```json
{"value":"{\"a\":1,\"b\":false,\"c\":\"abc\"}"}
```

... which is correct, but in some cases I need it to just pass through the raw JSON so I can make the result be:

```json
{"value":{"a":1,"b":false,"c":"abc"}}
```

I propose a `@rawjson` decorator:

```ts
@json
class Foo {
  @rawjson
  value: string;
}
```

Which would signal to the serialize and deserialize functions to just pass through anything in the string rather than attempt to encode or decode it.

Thanks.

**Comment by mattjohnsonpint** [comment]
It should also work with a `string | null` field, which would pass through `null` if set to `null`.  And it should also work in conjunction with `@omitnull`, `@omitif`, etc. existing attributes.

**Comment by JairusSW** [comment]
Assign a property the type `JSON.Raw` to signify a block of Raw JSON.
Example:
```js
class Foo {
  bar: JSON.Raw;
}
```
