### ISSUE TITLE
How is invalid/non-well-formed JSON handled while parsing

### ISSUE THREAD

**Issue by trieloff** [JairusSW/as-json#9]
Great to see another JSON parser for AssemblyScript. When dealing with JSON from external sources, it would be great to have some examples to see how erroneous JSON is handled. In particular:

- non-JSON, e.g. a missing `}` somewhere
- JSON with extraneous fields compared to the declared type
- JSON with mismatching fields compared to the declared type

**Comment by trieloff** [comment]
See also: https://github.com/near/assemblyscript-json/issues/225 – similar problem there

**Comment by JairusSW** [comment]
Ah, yes. I'm going to try to do this.
I need a schema checker (https://www.npmjs.com/package/is-my-json-valid)?
And a dynamic checker. (I'll make this myself).
I'll get back as soon as its done!

**Comment by JairusSW** [comment]
@trieloff, so sorry I'm so late in getting back. So, json-as does not have any error checking, so the JSON must be checked and verified beforehand. I created json-as to be a simple parser/stringifier that can be easily built off of. So, if you need to verify JSON, i would recommend checking on NPM for a similar package and writing it in AssemblyScript. :)

**Comment by JairusSW** [comment]
Maybe using a https://github.com/MaxGraey/as-option here or implement rust-like `Result<T>`?
