### ISSUE TITLE
Could not serialize data of type

### ISSUE THREAD

**Issue by prep** [JairusSW/as-json#97]
I cannot seem to get a basic example working and I cannot for the life of me figure out where I am making a mistake.

example.ts:
```typescript
import { JSON } from "json-as/assembly"

@json
class Foo {
    name: string
    age: i32
}

const foo: Foo = {
    name: "Alice",
    age: 30
}

// Because the runtime expects a waPC client. Can be ignored.
export function __guest_call(operation_size: usize, payload_size: usize): bool {
    return false
}

export function _start(): void {
    console.log("step 1")
    const encoded: string = JSON.stringify(foo)
    console.log("step 2")
    const decoded = JSON.parse<Foo>(encoded)
    console.log("step 3")
}
```

package.json:
```json
{
  "dependencies": {
    "@wapc/as-guest": "^0.3.1",
    "json-as": "^0.9.26",
    "visitor-as": "^0.11.4"
  },
  "devDependencies": {
    "assemblyscript": "^0.27.30"
  }
}
```

I compile it like:
```
JSON_DEBUG=true asc example.ts -o example.wasm --transform json-as/transform
```

This yields no output, though. I expected the `JSON_DEBUG=true` to print _something_ to stdout. Is that an indication that the transform operation isn't being executed?

When I run the wasm module I get this:
```
10:56:20.972431 env:console.log: step 1
10:56:20.972508 env:abort: Could not serialize data of type Foo. Make sure to add the correct decorators to classes. at ~lib/json-as/assembly/index.ts:210:7
```

Is there something obvious that I am missing?

**Comment by prep** [comment]
I found out what the problem was.

The `asc` command in my path was version `0.27.25` whereas the `assemblyscript` package installed the `0.27.30` (the latest). Using the proper `asc` command fixed the problem.

**Comment by JairusSW** [comment]
@prep, mhm, make sure your running the latest version of json-as as well
